/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/household/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddExpenseRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/household/settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddSettlementRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/household/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HouseholdSummaryDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivityCycleDto: {
            isSettled?: boolean;
            /** Format: date-time */
            startedAtUtc?: string;
            /** Format: date-time */
            settledAtUtc?: string | null;
            /** Format: double */
            netAtEnd?: number;
            items?: components["schemas"]["ActivityItemDto"][];
        };
        ActivityItemDto: {
            /** Format: date-time */
            occurredAtUtc?: string;
            type?: components["schemas"]["ActivityItemType"];
            description?: string | null;
            paidBy?: components["schemas"]["Payer"];
            from?: components["schemas"]["Payer"];
            to?: components["schemas"]["Payer"];
            /** Format: double */
            amount?: number;
            /** Format: double */
            netAfterThisItem?: number;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        ActivityItemType: 1 | 2;
        AddExpenseRequest: {
            /** Format: double */
            amount?: number;
            description?: string;
            /** Format: date */
            date?: string;
            paidBy?: string;
        };
        AddSettlementRequest: {
            /** Format: date */
            date?: string;
            from?: string;
            to?: string;
            /** Format: double */
            amount?: number;
            note?: string | null;
        };
        ErrorResponse: {
            error?: string;
        };
        HouseholdSummaryDto: {
            /** Format: int32 */
            year?: number;
            /** Format: int32 */
            month?: number;
            /** Format: double */
            total?: number;
            /** Format: double */
            totalPaidByMe?: number;
            /** Format: double */
            totalPaidByPartner?: number;
            /** Format: double */
            netOwedToMe?: number;
            /** Format: double */
            netOwedToPartner?: number;
            recentActivityCycles?: components["schemas"]["ActivityCycleDto"][];
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        Payer: 0 | 1;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
